version: "3.8"

services:

  ss_app:
    container_name: ss_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    networks:
      - ss_network

  ss_nginx:
    container_name: ss_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
    - ./public:/usr/src/app/public
    ports:
      - 8082:80
    depends_on:
      - ss_app
    environment:
      NGINX_FPM_HOST: ss_app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - ss_network

networks:
  ss_network:
    driver: bridge

volumes:
  ss-data: